// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookSystemDB.Entities;

[Index("Title", Name = "UQ__Books__2CB664DCC5B7F7B0", IsUnique = true)]
public partial class Book
{
    [Key]
    [StringLength(20)]
    public string ISBN { get; set; }

    [Required]
    [StringLength(100)]
    public string Title { get; set; }

    public int YearPublished { get; set; }

    public int GenreId { get; set; }

    public int AuthorId { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("Books")]
    public virtual Author Author { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("Books")]
    public virtual Genre Genre { get; set; }

    [InverseProperty("ISBNNavigation")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}