// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookSystemDB.Entities;

public partial class Rating
{
    [Key]
    public int RatingId { get; set; }

    [Required]
    [StringLength(20)]
    public string Description { get; set; }

    [InverseProperty("Rating")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}