// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookSystemDB.Entities;

public partial class Review
{
    [Key]
    public int ReviewId { get; set; }

    [Required]
    [StringLength(20)]
    public string ISBN { get; set; }

    [Required]
    [StringLength(100)]
    public string Reviewer { get; set; }

    public int RatingId { get; set; }

    [Required]
    [StringLength(100)]
    public string Comment { get; set; }

    [ForeignKey("ISBN")]
    [InverseProperty("Reviews")]
    public virtual Book ISBNNavigation { get; set; }

    [ForeignKey("RatingId")]
    [InverseProperty("Reviews")]
    public virtual Rating Rating { get; set; }
}